markdown: rdiscount
permalink: /:title/
url: http://dhuliu.github.io/blog/
name: dhuliu
author: dhuliu
email: dhull@163.com
duoshuo: dhuliu
cnzz: 119959
github: dhuliu
pygments: true
safe: true
paginate: 20
about: "这里是 dhuliu 的个人博客"
